[workspace]
members = [
  "libs/proto",
  "libs/sdk",
  "services/cli",
  "services/controlplane",
  "services/registry", "services/worker",
]

exclude = [
  "examples/echo",
  "examples/custom",
]

resolver = "2"
