[project]
name="echo"
version="0.1.0"

[build]
type = "custom"
script="""
set -e
cargo build --release --target x86_64-unknown-linux-musl
cp target/x86_64-unknown-linux-musl/release/echo $OUTPUT/bootstrap
"""
